const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
function setup() {
  let count=0;
  const context = vm.createContext({taskState:{},document:{addEventListener(){}},toDateKey:()=> '2026-09-17',createId:()=>String(++count),saveTasks(){},getBehavior:()=>({sessions:[],dailyPlans:{}})});
  vm.runInContext(fs.readFileSync('life.js','utf8'),context);
  return context;
}
function pkg() {return {version:1,id:'page-1',date:'2026-09-17',text:'Walked 20 minutes.',records:[{title:'Walk',domain:'Movement',kind:'activity',completed:true,minutes:20,effort:3,evidence:'Walked 20 minutes.'}],actions:[{id:'renew-id',title:'Renew document',domain:'Personal tasks',priority:'important',nextAction:'Find requirements'}]};}
test('import preserves evidence and rejects duplicate package ids',()=>{const c=setup();const p=c.validateLifeImport(pkg());c.lifeCommit(p);assert.equal(c.taskState.life.records.length,1);assert.throws(()=>c.lifeCommit(p),/already/);assert.equal(c.taskState.life.entries.length,1);});
test('rejects invented evidence, impossible dates and negative durations',()=>{const c=setup();let p=pkg();p.records[0].evidence='Worked 80 minutes';assert.throws(()=>c.validateLifeImport(p),/excerpt/);p=pkg();p.date='2026-02-30';assert.throws(()=>c.validateLifeImport(p),/date/);p=pkg();p.records[0].minutes=-1;assert.throws(()=>c.validateLifeImport(p),/Minutes/);});
test('observations cannot become completed actions',()=>{const c=setup();const p=pkg();p.records[0].kind='observation';const r=c.validateLifeImport(p);assert.equal(r.records[0].completed,false);});
test('journal duration is not merged with timer duration',()=>{const c=setup();c.lifeCommit(c.validateLifeImport(pkg()));const d=c.lifeDay('2026-09-17');assert.equal(d.reported,20);assert.equal(d.minutes,0);assert.equal(d.completed,1);});
test('import adds persistent actions and preserves effort scoring',()=>{const c=setup();const p=c.validateLifeImport(pkg());c.lifeCommit(p);assert.equal(c.lifeStore().actions.length,1);assert.equal(c.lifeStore().actions[0].priority,'important');assert.equal(c.lifeStore().records[0].effort,3);});
test('backdated assistant import updates Rhythm and closes an action on the journal day',()=>{const c=setup();const data=pkg();data.rhythm=[{habitId:'water',value:2,evidence:'Walked 20 minutes.'},{habitId:'breakfast',value:1,evidence:'Walked 20 minutes.'}];data.actionUpdates=[{id:'renew-id',status:'done',priority:'important',deadline:'2026-09-17'}];const validated=c.validateLifeImport(data);c.lifeCommit(validated);assert.equal(c.taskState.rhythm.events.length,2);assert.equal(c.taskState.rhythm.events.find(event=>event.habitId==='water').value,2);assert.equal(c.lifeStore().actions[0].completedAt,'2026-09-17T12:00:00.000Z');assert.equal(c.lifeStore().actions[0].deadline,'2026-09-17');});
test('backdated assistant import preserves containment truth',()=>{const c=setup();const data=pkg();data.containment={status:'breach',boundary:'astrology',boundaries:['astrology','social'],note:'Watched astrology and Snapchat.'};const validated=c.validateLifeImport(data);c.lifeCommit(validated);assert.equal(c.lifeStore().innerCommand.containmentDays[0].status,'breach');assert.deepEqual([...c.lifeStore().innerCommand.containmentDays[0].boundaries],['astrology','social']);});
test('reviewed assessment is capped at ten and stored once per day',()=>{const c=setup();const data=pkg();data.assessment={scores:{priority:3,resistance:2,foundation:2,spiritual:1,closure:1,containment:1},note:'Strong execution.'};c.lifeCommit(c.validateLifeImport(data));assert.equal(c.lifeStore().dailyAssessments.length,1);assert.equal(c.lifeStore().dailyAssessments[0].total,10);assert.equal(c.lifeStore().dailyAssessments[0].qualified,true);});
test('assessment requires meaningful priority work to qualify',()=>{const c=setup();const data=pkg();data.assessment={scores:{priority:0,resistance:2,foundation:2,spiritual:1,closure:1,containment:1}};c.lifeCommit(c.validateLifeImport(data));assert.equal(c.lifeStore().dailyAssessments[0].total,7);assert.equal(c.lifeStore().dailyAssessments[0].qualified,false);});
test('assessment rejects score inflation',()=>{const c=setup();const data=pkg();data.assessment={scores:{priority:4,resistance:2,foundation:2,spiritual:1,closure:1,containment:1}};assert.throws(()=>c.validateLifeImport(data),/priority score/);});
