const { chromium } = require('playwright');
const { pathToFileURL } = require('node:url');
const path = require('node:path');
const assert = require('node:assert/strict');

(async () => {
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  try {
    const page = await browser.newPage({ viewport: { width: 1360, height: 900 } });
    const errors = [];
    page.on('pageerror', error => errors.push(error.message));
    await page.goto(pathToFileURL(path.resolve('index.html')).href);
    await page.locator('#unlock-pass').fill('9619');
    await page.getByRole('button', { name: 'Enter KRYOS' }).click();
    await page.getByRole('button', { name: 'Money', exact: true }).first().click();
    assert.equal(await page.locator('.money-metric').count(), 3);
    await page.getByRole('button', { name: 'Add split' }).click();
    await page.locator('#money-form [name=verifiedDate]').fill('2026-09-26');
    await page.locator('#money-form [name=card]').fill('1000');
    await page.locator('#money-form [name=friendCard]').fill('700');
    await page.locator('#money-form [name=ownCard]').fill('200');
    await page.locator('#money-form [name=direct]').fill('100');
    await page.locator('#money-form [name=request]').fill('100');
    await page.getByRole('button', { name: 'Save record' }).click();
    assert.match(await page.locator('.money-form-error').textContent(), /must equal/);
    await page.locator('#money-form [name=ownCard]').fill('300');
    await page.getByRole('button', { name: 'Save record' }).click();
    assert.equal(await page.evaluate(() => moneySettlement().differenceCents), 0);
    assert.match(await page.locator('.money-reconcile').first().textContent(), /matches to the cent/);
    await page.evaluate(() => { moneyStore().settlement.details = [{ label: 'Returned payment', amountCents: 500, note: 'Reversed, with no payment credit.' }]; moneyStore().settlement.historicalInterest = { friendCents: 4000, ownCents: 200 }; renderMoneyView(); });
    assert.match(await page.locator('.money-evidence-panel').textContent(), /Returned payment/);
    assert.match(await page.locator('.money-historical-interest').textContent(), /\$40\.00/);
    assert.match(await page.locator('.money-living').textContent(), /Interest changes the number/);
    await page.evaluate(() => { moneyStore().statementCycles = [{ cycleStart:'2026-01-01', cycleClose:'2026-01-31', paymentDueDate:'2026-02-20', closingBalanceCents:300000, minimumDueCents:10000, purchaseInterestCents:50, promoInterestCents:7000, purchaseAprBasisPoints:2849, promoAprBasisPoints:2849, balanceSubjectToInterestCents:305000, sourceStatementHash:'a'.repeat(64) }]; renderMoneyView(); });
    assert.match(await page.locator('.money-statement-evidence').textContent(), /Interest pressure/);
    assert.equal(await page.locator('.money-pressure-chart').count(), 1);
    await page.getByRole('button', { name: 'Record card payment' }).first().click();
    await page.locator('#money-form [name=date]').fill('2026-09-27');
    await page.locator('#money-form [name=amount]').fill('50');
    await page.locator('#money-form [name=owner]').selectOption('friend');
    await page.locator('#money-form [name=funder]').selectOption('own');
    await page.locator('#money-form [name=note]').fill('Test statement payment');
    await page.getByRole('button', { name: 'Save record' }).click();
    assert.equal(await page.evaluate(() => KryosMoneyEngine.position(moneySettlement(), moneyStore().ledgerEvents).directCents), 15000);
    await page.getByRole('button', { name: 'Post statement interest' }).click();
    await page.locator('#money-form [name=startDate]').fill('2026-09-27');
    await page.locator('#money-form [name=date]').fill('2026-09-30');
    await page.locator('#money-form [name=amount]').fill('12');
    await page.locator('#money-form [name=closing]').fill('962');
    await page.locator('#money-form [name=note]').fill('Test issuer interest charge');
    await page.getByRole('button', { name: 'Save record' }).click();
    assert.equal(await page.evaluate(() => moneyStore().ledgerEvents.filter(e => e.type === 'statement-interest').length), 1);
    assert.equal(await page.evaluate(() => KryosMoneyEngine.position(moneySettlement(), moneyStore().ledgerEvents).cardCents), 96200);
    await page.getByRole('button', { name: 'Open call brief' }).first().click();
    assert.equal(await page.locator('.money-call-focus').count(), 1);
    assert.match(await page.locator('.money-focus-amount').textContent(), /\$150\.00/);
    await page.getByRole('button', { name: 'Overview' }).click();
    assert.equal(await page.locator('.money-metric').count(), 3);
    assert.deepEqual(errors, []);
    console.log('PASS: Money checkpoint validation, reconciliation, and call focus');
  } finally {
    await browser.close();
  }
})().catch(error => { console.error(error); process.exitCode = 1; });
