import test from 'node:test';
import assert from 'node:assert/strict';
import '../supabase/functions/kryos-ingest/sadhana-core.js';
import {projectRequest} from '../supabase/functions/kryos-ingest/projector.mjs';
const C=globalThis.KryosSadhana;
let sequence=0;
const date='2026-10-10',now='2026-10-11T18:00:00Z';
function fixture(){return {actions:[],innerCommand:{covenant:{startDate:'2026-09-26',endDate:'2026-11-12'},containmentDays:[{date:'2026-09-26',status:'breach'}]}};}
function apply(life,op,key){return C.apply(life,op,date,now,key||'test-'+(++sequence));}
function ready(life){apply(life,{type:'plan.empty'});for(const item of C.items.filter(i=>i.type!=='guidance'))apply(life,{type:'item.set',itemId:item.id,value:'kept'});}
test('48 calendar dates include DST change and retain earlier cycle',()=>{const life=fixture();C.ensure(life);assert.equal(C.dates().length,48);assert.equal(C.number('2026-10-09'),0);assert.equal(C.number('2026-11-26'),48);assert.equal(C.dates().at(-1),'2026-11-26');assert.equal(life.sadhana.previousCycles[0].records.length,1);C.ensure(life);assert.equal(life.sadhana.previousCycles.length,1);});
test('unknown facts stay open; explicit full review wins',()=>{const life=fixture();assert.equal(C.evaluate(life,date).status,'open');assert.throws(()=>apply(life,{type:'day.review'}));ready(life);assert.equal(C.evaluate(life,date).status,'open');apply(life,{type:'day.review'});assert.equal(C.evaluate(life,date).status,'won');});
test('one missed quantity loses despite completing other commitments',()=>{const life=fixture();ready(life);apply(life,{type:'task.assign',title:'Synthetic target',kind:'quantity',target:55});const task=life.sadhana.days[date].tasks[0];apply(life,{type:'task.progress',taskId:task.id,value:54});apply(life,{type:'day.review'});assert.equal(C.evaluate(life,date).status,'not-won');assert.equal(life.actions[0].status,'open');apply(life,{type:'task.progress',taskId:task.id,value:55});assert.equal(C.evaluate(life,date).status,'won');assert.equal(life.actions[0].status,'done');});
test('multi-boundary incident blocks win; correction retains audit and requires reconfirmation',()=>{const life=fixture();ready(life);apply(life,{type:'breach.record',boundaries:['instagram','validation'],note:'Synthetic incident'});apply(life,{type:'day.review'});assert.equal(C.evaluate(life,date).status,'not-won');const id=life.sadhana.days[date].breaches[0].id;apply(life,{type:'breach.correct',breachId:id,reason:'Wrong date'});assert.equal(C.evaluate(life,date).status,'open');assert.ok(life.sadhana.history.length);});
test('Actions completion and reopening update linked day; later actual work cannot win earlier day',()=>{const life=fixture();ready(life);apply(life,{type:'task.assign',title:'Synthetic check',kind:'check'});const action=life.actions[0];action.status='done';C.actionChanged(life,action,'2026-10-11',now);apply(life,{type:'day.review'});assert.equal(C.evaluate(life,date).status,'not-won');C.actionChanged(life,action,date,now);assert.equal(C.evaluate(life,date).status,'won');action.status='open';C.actionChanged(life,action,date,now);assert.equal(C.evaluate(life,date).status,'not-won');});
test('idempotent retry does not duplicate tasks and mismatch is rejected',()=>{const life=fixture(),op={type:'task.assign',title:'Synthetic task',kind:'check'};apply(life,op,'same');apply(life,op,'same');assert.equal(life.actions.length,1);assert.equal(life.sadhana.days[date].tasks.length,1);assert.throws(()=>apply(life,{...op,title:'Different'},'same'));});
test('future plan allowed; future completion and early battle review rejected',()=>{const life=fixture();C.apply(life,{type:'task.assign',title:'Synthetic future',kind:'check'},date,'2026-10-09T15:00:00Z','future');assert.throws(()=>C.apply(life,{type:'item.set',itemId:'instagram',value:'kept'},date,'2026-10-09T15:00:00Z','future2'));assert.throws(()=>C.apply(life,{type:'day.review'},date,'2026-10-10T15:00:00Z','early'));});
test('stale revision is rejected; corrected target keeps original history',()=>{const life=fixture();apply(life,{type:'task.assign',title:'Synthetic count',kind:'quantity',target:10});const t=life.sadhana.days[date].tasks[0];assert.throws(()=>apply(life,{type:'task.progress',taskId:t.id,value:4,expectedRevision:0}));apply(life,{type:'task.correct',taskId:t.id,target:8,reason:'Typo'});assert.equal(life.sadhana.history.at(-1).before.tasks[0].target,10);});
test('assistant plan uses shared engine and updates existing Actions identity',()=>{const request={schema_version:1,idempotency_key:'synthetic-plan',local_date:date,timezone:'America/Chicago',raw_text:'Assign synthetic task.',operations:[{type:'sadhana.task.assign',title:'Synthetic task',kind:'check',evidence_quote:'Assign synthetic task.'}]};const projected=projectRequest(request,{life:fixture()},{},now);assert.equal(projected.tasksChanged,true);assert.equal(projected.tasks.life.sadhana.days[date].tasks[0].actionId,projected.tasks.life.actions[0].id);assert.equal(projected.effects[0].area,'Inner Command');});
